version: "3.9"
services:
  app:
    build:
      context: .
    container_name: frontend-metadados
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
